version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  web:
    depends_on:
      - db
    build: .
    ports:
      - "8082:80"
    restart: always
